/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Primary colors from design system
        "on-tertiary": "#ffffff",
        outline: "#74777f",
        "surface-variant": "#e0e3e5",
        "primary-container": "#1a365d",
        "inverse-surface": "#2d3133",
        "tertiary-container": "#003f21",
        "surface-container-highest": "#e0e3e5",
        "on-tertiary-fixed": "#00210f",
        "secondary-fixed": "#d9e3f8",
        "on-secondary-container": "#5b6577",
        "outline-variant": "#c4c6cf",
        "surface-bright": "#f7fafc",
        "surface-container-high": "#e5e9eb",
        background: "#f7fafc",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#bdc7db",
        "on-surface-variant": "#43474e",
        "on-primary-fixed-variant": "#2d476f",
        "surface-container": "#ebeef0",
        primary: "#002045",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3e4758",
        "surface-tint": "#455f88",
        "on-primary-fixed": "#001b3c",
        "inverse-primary": "#adc7f7",
        "on-surface": "#181c1e",
        "inverse-on-surface": "#eef1f3",
        "surface-dim": "#d7dadc",
        "on-tertiary-fixed-variant": "#00522c",
        surface: "#f7fafc",
        secondary: "#555f70",
        "primary-fixed-dim": "#adc7f7",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "primary-fixed": "#d6e3ff",
        "on-tertiary-container": "#3fb371",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#6bdc96",
        "surface-container-low": "#f1f4f6",
        "secondary-container": "#d9e3f8",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        tertiary: "#002712",
        "tertiary-fixed": "#88f9b0",
        "on-primary-container": "#86a0cd",
        "on-background": "#181c1e",
        "on-secondary-fixed": "#121c2b",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      fontSize: {
        xs: ["12px", "16px"],
        sm: ["14px", "20px"],
        base: ["16px", "24px"],
        lg: ["18px", "28px"],
        xl: ["20px", "32px"],
        "2xl": ["24px", "36px"],
        "3xl": ["32px", "40px"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
